Feature/8 회원가입/로그인/로그아웃 구현
f-lab-edu/swimmer pull request #14
Opened 2024-06-28 04:34 UTC by jjisabi

## 변경 사항

* .env 파일에 firebaseConfig 정의

* firestore.tsx 파일에 firebase 로그인/로그아웃/회원가입 함수 정의

* 회원가입 구현
  * Firebase Authentication의 createUserWithEmailAndPassword() 함수 사용
  * 로그인 성공 시 main 페이지로 이동
  
* 로그인 구현
  * signInWithEmailAndPassword() 함수 사용
  * 로그인 성공 시 main 페이지로 이동
  * HEADER  상단에 로그인 한 user 정보 표시
  * 표시 된 user 정보 div 태그 클릭 시 마이 페이지로 이동
  
* 로그아웃 구현
  * signOut() 함수 사용

2024-06-28 06:29 UTC, joonhok-fittube requested changes

2024-06-28 06:29 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +        router.push("/login");
여기서 이렇게 /login 페이지로 이동시킬 수도 있지만, `userCredential`을 가지고 바로 로그인 시켜줄 수도 있습니다. 방금 회원 가입한 사용자니까 로그인 시켜주는게 더 좋을 것 같습니다.

2024-06-28 06:29 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +        if(error.code === 'auth/email-already-in-use'){
현재 코드가 포매팅이 안돼 있는 것 같습니다. VS Code에 prettier extension을 설치하시고 ALT+SHIFT+F 키를 누르면 포매팅이 됩니다. 

시간 여유가 가능하시다면 husky를 설치하셔서 커밋하기 전에 자동으로 prettier가 실행되도록 설정해주세요.

2024-06-28 06:29 UTC, joonhok-fittube commented on src/components/signup.tsx
> +        if(password.length <= 6){
18번째 라인에서는 `password.length < 6`로 검사하고 있는데 검사 규칙이 서로 다릅니다. 이런 실수가 생기지 않도록 검사 규칙을 따로 함수로 빼내서 사용해주세요.

2024-06-28 06:29 UTC, joonhok-fittube commented on src/components/signup.tsx
> +        if (email === '' || password.length < 6) {
`validate()`를 이미 했는데 중복해서 실행되네요.

2024-06-28 06:29 UTC, joonhok-fittube commented on src/components/header.tsx
> +        authService.onAuthStateChanged((user) => {
리액트에서 authentication 정보는 렌더링 트리 여러 군데에서 필요하기 때 보통 context로 처리합니다. 

https://kentcdodds.com/blog/authentication-in-react-applications

이 링크를 참조해서 리팩토링해주세요.

2024-07-01 06:54 UTC, joonhok-fittube requested changes
이렇게 고쳐서는 alert 다이얼로그가 뜨면서, 또는 alert 다이얼로그가 뜬 다음 닫힐 때 `signUp()` 함수가 실행됩니다. validation이 실패할 때는 `signUp()` 함수가 실행되지 않도록 바꿔주세요.

2024-07-01 06:59 UTC, joonhok-fittube requested changes

2024-07-01 06:59 UTC, joonhok-fittube commented on src/components/header.tsx
> +    const userName = useAuthState().split('@')[0];
여기서 `.split('@')[0]` 부분이 꼭 필요한가죠? 우리는 지금 사용자가 로그인한 상태인지 아닌지만 판단하면 충분하지 않나요?

2024-07-01 06:59 UTC, joonhok-fittube commented on src/contexts/AuthContext.tsx
> +  const [userName, setUserName] = useState<string>('');
기본값을 빈 스트링으로 사용하지 마시고 `null`로 쓰시는게 조금더 읽기가 편하고 의미 전달이 명확할 것 같습니다.

2024-07-01 07:35 UTC, jjisabi commented on src/components/header.tsx
> +    const userName = useAuthState().split('@')[0];
맞습니다. 말씀하신대로 split() 함수 제거하겠습니다. 
화면에 표시할 때는 유저의 이메일에서 아이디 부분만 표시하고 싶은데 
`<button>{userName.split('@')[0]}님<button/>` 으로 변경해도 괜찮을까요?

2024-07-02 06:28 UTC, joonhok-fittube approved these changes
네, 수고하셨습니다!

2024-07-02 07:04 UTC, jjisabi commented
감사합니다 !

2024-07-02 07:09 UTC, merged