Feature/9 로그인 정보로 데이터 조회/추가 처리
f-lab-edu/swimmer pull request #16
Opened 2024-07-03 14:30 UTC by jjisabi

## 변경 사항

* firestore 구조 변경, 코드 수정
  * `reviews`, `swimming_pool` collection 데이터 fetch
 
* 리뷰 작성 시 현재 로그인 한 user 데이터 전달
  * `writeLayout.tsx` 파일에서 기존 하드코딩으로 처리 했던 user를 로그인 context의 user로 변경
 
* 현재 로그인 한 유저가 방문한 수영장 조희
  * `reviews` collection의 user와 로그인 context의 user가 일치하면 데이터 반환
  * ` firestore.tsx `파일에서 `reviews`, `swimming_pool` collection fetch한 후 수영장 id가 같으면 `totalData`로 반환
  
* 로그인 인증 상태 유지
  * `setPersistence`() 메소드 이용하여 현재 session, 탭에서만 인증 상태 유지

2024-07-05 06:46 UTC, joonhok-fittube requested changes

2024-07-05 06:46 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +      fetchedData.push(reviewData);
이 부분은 `reviews` 콜렉션에 `id` 필드가 `id`와 동일한 문서를 찾는 코드인데, 이렇게 전체 문서를 받아온 다음 순회하는 것이 아니라 간단한 쿼리 코드로 작성할 수 있습니다. 다음 링크를 참조해서 리팩토링해주세요.

https://firebase.google.com/docs/firestore/query-data/queries?_gl=1*it4zcv*_up*MQ..*_ga*MzE0Mjc1OTU0LjE3MjAxNjAyNTg.*_ga_CW55HF8NVT*MTcyMDE2MDI1Ny4xLjAuMTcyMDE2MDI1Ny4wLjAuMA..#simple_queries

2024-07-05 06:46 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +    await setDoc(doc(db, 'reviews', uuidv4()), {
이 경우 처럼 도큐멘트 id 를 지정하지 않고 도큐멘트를 추가할 때는 `addDoc()` api를 사용하시면 더 편리합니다.

https://firebase.google.com/docs/firestore/manage-data/add-data?_gl=1*qccoi5*_up*MQ..*_ga*MzE0Mjc1OTU0LjE3MjAxNjAyNTg.*_ga_CW55HF8NVT*MTcyMDE2MDI1Ny4xLjAuMTcyMDE2MDI1Ny4wLjAuMA..#add_a_document

2024-07-05 06:46 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +    await setDoc(doc(db, 'swimming_pools', data.id), {
지금은 2개의 네트워크 통신이 직렬적으로 실행되는데, 조금 더 작업을 빨리 처리하기 위해 `Promise.all([])`을 이용해서 병렬로 처리해주세요.

2024-07-05 06:46 UTC, joonhok-fittube commented on src/components/writeLayout.tsx
> +      user: user.displayName ? user.displayName : '',
이 구문은 `user.displayName ?? ''`로 줄여 적을 수 있습니다.

2024-07-05 06:46 UTC, joonhok-fittube commented on src/components/mypage.tsx
> +  function ReviewList({reviews}: {reviews: ReviewData[]}) {
보통 이렇게 렌더링 트리의 일부를 별도의 컴포넌트로 분리해낼 때는 원 함수형 컴포넌트(지금 이 경우는 `Layout` 함수) 바깥에 선언합니다. `ReviewList` 함수 안에서 `Layout` 함수의 스코프에 접근할 일이 있는 특별한 경우가 아니면 그렇게 해야 `Layout` 함수의 복잡도가 낮아지고 코드 가독성이 높아집니다.

2024-07-05 06:46 UTC, joonhok-fittube commented on src/components/header.tsx
> +    <>
이 React Fragment는 불필요하네요.

2024-07-05 06:46 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +export async function fetchReviewData(id: string = '') {
여기서 `id`가 정확히 어떤 아이디인지 명확하게 이름을 지어주는게 좋겠습니다. 커밋 제목을 보면 `user_id` 가 돼야될 것 같은데 맞을까요?

그리고 그게 맞다면 review 도큐멘트에는 `id`외에 `user_id` 또는 `author_user_id` 같은 속성을 추가하셔야 될 것 같습니다.

2024-07-05 06:46 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +      return pool.id === review.id;
여기서 `pool.id === review.id` 이렇게 비교하는게 맞나요? review 데이터에 `swimmingpool_id` 속성이 추가되고 그 속성이랑 `pool.id` 를 비교하는 것이 맞을 것 같습니다.

2024-07-05 06:46 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +    if (id === '' || doc.data()['id'] === id) {
다른 코멘트에서도 적었듯이 이 부분은 firestore의 query 기능을 이용해 간단히 만들 수 있습니다. 

먼저 현재 로그인한 사용자가 작성한 리뷰를 전부 읽어오고 그 다음 그 리뷰들에 연결된(포함된) 수영장 id 값들로 수영장 정보를 다시 읽어와서 그 두 쿼리를 합쳐서 데이터를 만들면 되겠습니다.

2024-07-05 09:43 UTC, jjisabi commented on src/data/firestore.tsx
> +export async function fetchReviewData(id: string = '') {
여기서 id는 수영장 고유번호 id입니다. 제가 헷갈리게 이름을 지었네요. 
swimmingPool_id로 변경하고 도큐먼트도 변경하겠습니다.

2024-07-05 09:48 UTC, jjisabi commented on src/data/firestore.tsx
> +      return pool.id === review.id;
reviews 컬렉션 필드에 id가 수영장 고유 번호이고, swimming_pool 컬렉션 필드에 id도 수영장 고유 번호입니다. 그래서 수영장 번호(수영장)가 일치하면 데이터를 불러올 수 있도록 하였습니다. 제가 이해한 이 내용이 맞다면, 위의 코멘트와 같이 id필드 명을 변경하면 될 것 같습니다. 맞을까요?

2024-07-08 07:00 UTC, joonhok-fittube requested changes

2024-07-08 07:00 UTC, joonhok-fittube commented on src/components/writeLayout.tsx
> +      user: user.displayName ?? user.displayName,
`user: user.displayName ?? user.displayName,` 가 아니고
`user: user.displayName ?? ''` 입니다. 

`??`는 nullish coalescing 연산자입니다. 다음 링크를 공부해주세요.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

2024-07-08 07:00 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +  user: string | null;
그래서 여기는 그대로 `user: string;` 이어야 합니다.

2024-07-08 07:00 UTC, joonhok-fittube commented on src/components/mypage.tsx
> +            review => review.author_user_id === user.displayName,
`user`객체에는 `uid` 속성이 있습니다. 파이어스토어 `author_user_id` 속성에 저장할 때도 `uid` 속성을 이용할 것이고, 여기서도 그 속성을 이용해 필터링 해야 합니다. `displayName`은 사용자가 임의로 지정하고 변경할 수 있는 서비스 내의 닉네임 같은 것입니다.

https://firebase.google.com/docs/reference/node/firebase.User?_gl=1*190kdxg*_up*MQ..*_ga*MTY4NTk4NTg5MS4xNzIwNDIxMTIw*_ga_CW55HF8NVT*MTcyMDQyMTEyMC4xLjAuMTcyMDQyMTEyMC4wLjAuMA..#uid

2024-07-08 07:00 UTC, joonhok-fittube commented on src/data/firestore.tsx
>          reg_date: doc.data()['reg_date'],
여기도 그렇고 뒷 부분에서도 필드 이름을 변경하지 않는 경우에는 이렇게 새로운 객체를 만들필요 없이 `doc.data()`를 그대로 쓰시면 됩니다.

그래서 58번째 줄부터 67번째 줄까지는 그냥
`const reviewsData = reviewsQuerySnapshot.map(snap => snap.data())`
라고 처리하시면 됩니다. 밑에 수영장 부분도 마찬가지고요.

2024-07-08 07:00 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +    const reviewsQuery =
슬랙에서 말씀하신 대로 `fetchReviewData` 함수가 2군데에서 서로 다른 사용례로 쓰이고 있습니다. 이 함수를 둘로 나눠서
`fetchReviewsBySwimmingPoolId()` 랑 `fetchReviewByUserId()`로 나눠주세요. 

지금은 현재 로그인한 사용자의 리뷰만 가져오는게 아니라 리뷰 전체를 다 가져오고 있는데, 함수를 2개로 나누면서 그것도 고쳐주세요.

2024-07-08 07:00 UTC, joonhok-fittube commented on src/components/mypage.tsx
> +        review => review.author_user_id === user.displayName,
여기도 `review.author_user_id === user.uid`로 바꿔야 합니다.

2024-07-08 07:00 UTC, joonhok-fittube commented on src/lib/types.tsx
> +  swimmingpool_address: string;
`ReviewData`에는 `swimmingpool_id`만 있으면 되고 `swimmingpool_address`나 `swimmingpool_name`는 있으면 안됩니다. 이 정보들은 수영장 컬렉션에 저장돼있어야 되고 `swimmingpool_id`로 수영장 컬렉션의 문서를 읽어와서 받아와야 되는 정보입니다. 그렇지 않으면 같은 데이터가 두 컬렉션에 중복으로 존재하게 돼서 문제가 발생합니다.

2024-07-08 08:30 UTC, jjisabi commented on src/components/mypage.tsx
> +            review => review.author_user_id === user.displayName,
firestore에 reviews collection에서 author_user_id 속성에 저장 값이 `uid`속성 값이어야 한다는 말씀 맞을까요?
그럼 `author_user_id`는 `uid` 속성 값, `user`(user_name)은 `displayName`값 이렇게 저장되는 것 맞을까요?

```
author_user_id: "cvQHVhb5WdPtMrWDXzY333mjJ9m2"
user_name: "user1"
```

2024-07-09 05:07 UTC, joonhok-fittube commented on src/components/mypage.tsx
> +            review => review.author_user_id === user.displayName,
네, 그렇게 저장하시면 됩니다. 근데 review 도큐멘트에는 user_name이나 displayName이 저장될 필요는 없습니다. uid 값만 저장하면 사용자를 특정할 수 있으니까요.

2024-07-09 05:22 UTC, joonhok-fittube approved these changes
간단한 코멘트 몇 개만 추가하였습니다. 수고 많으셨습니다.

2024-07-09 05:22 UTC, joonhok-fittube commented on src/components/writeLayout.tsx
> +      user_name: user?.email?.split('@')[0] ?? '',
이런 작업은 이렇게 개별 컴포넌트에서 하지 마시고 AuthContext에서 한 번에 처리하고 개별 컴포넌트에서는 거기서 처리된 값을 쓰시는 편이 낫습니다.

2024-07-09 05:22 UTC, joonhok-fittube commented on src/contexts/AuthContext.tsx
> -        setDisplayName(user.email ? user.email.split('@')[0] : null);
유저와 관련된 작업은 이곳에서 다 처리하고 나머지 컴포넌트들에서는 이 곳에서 처리된 값을 읽기 전용으로 받아와서 사용하도록 처리해주세요.

이 부분은

```
import { updateCurrentUser } from "firebase/auth"

if (!user.displayName) {
  const displayName = user.email.split('@')[0];
  updateCurrentUser({...user, displayName})
}
```

정도로 처리하시면 될 것 같습니다.

2024-07-09 05:22 UTC, joonhok-fittube commented on src/components/header.tsx
> +  const AuthenticatedUserControls = ({user}: {user: User | null}) => {
이 부분도 Header 바깥으로 빼주시고, `user` 객체가 있을 때와 없을 때도 각각 별도의 컴포넌트로 분리해 주세요.

2024-07-09 05:22 UTC, joonhok-fittube commented on src/lib/types.tsx
> +  author_user_name: string;
사실 리뷰 데이터에 user name이 포함되는건 이상합니다. 그런데 일단 우리는 프론트엔드에 집중하기 위해서 이 부분은 넘어가겠습니다. 원래대로라면 여기는 user_id만 저장하고, user 콜렉션이 따로 있어서 이 리뷰 작성자의 username은 user 콜렉션을 조회해서 받아와야 합니다.

2024-07-09 11:15 UTC, merged