Style/1 화면 UI 마이그레이션/ 사용자 레벨, 지도 API 구현
f-lab-edu/swimmer pull request #18
Opened 2024-07-12 05:45 UTC by jjisabi

## 1. 화면 UI 마이그레이션 2. 사용자 레벨 구현 3. 지도 API 구현
  * 화면 UI 마이그레이션
    * NextUI Component 적용
      * `basicLayout.tsx` 파일의 수영장 리스트 Card Component 적용
      * 로딩바 Spinner Component 적용
    * 회원가입/ 로그인 레이블 영문 -> 한글로 변경
    * `detailLaytou.tsx` 파일에 수영장 img 추가 
      * 5개 사진 URL 배열 데이터  반복하여 출력
    * `detailLaytou.tsx` 파일에서 상세 정보/리뷰가 없는 경우 '데이터 준비 중' 표시 출력
    
  * 리뷰 작성(인증) 횟수에 따라 사용자 레벨 구현 
    * Firestore에서 모든 리뷰 fetch하고, 사용자 별 리뷰 개수를 count 
    * count 결과로 내림차순하여 상위 3명 return

  * KakaoMap API 호출
    * "react-kakao-maps-sdk" 라이브러리 사용
    * `fetchReviewByUserId()` 함수에서 받은 `combinedData`의 `swimmingpool_address` 필드값을 기반으로 지도에 Mark 표시

2024-07-13 11:28 UTC, joonhok-fittube requested changes
수고하셨습니다. 코멘트 확인해주세요.

2024-07-13 11:28 UTC, joonhok-fittube commented on src/components/detailLayout.tsx
> +          item.IRREGULR_RELYSWIMPL_LANE_CNT) !== null ? (
또 한 가지 추천드리자면 `IRREGULR_RELYSWIMPL_LANE_CNT` 같이 공공 API에서 사용되는 속성 이름을 그대로 쓰지 말고 이 프로젝트 안에서 커스텀 타입을 하나 정의해서 1:1로 속성을 대응시키고 속성 이름들은 조금 더 이해하기 쉬운 이름으로 바꿔주세요. 그럼 코드를 작성하고 유지/관리하기 더 쉬워질 겁니다.

2024-07-13 11:28 UTC, joonhok-fittube commented on src/components/header.tsx
> +  const userName = user?.uid;
이 변수는 코드 그대로 `uid` 또는 `userUid`로 하는게 더 좋습니다. 보통 `userName`이라고 하면 서비스 내에서 표시되는 닉네임 같은 것을 말합니다.

2024-07-13 11:28 UTC, joonhok-fittube commented on src/components/header.tsx
>  const WithAuthenticatedUserControls = ({user}: {user: User | null}) => {
이 컴포넌트는 `user`가 null이 아닐 때만 렌더링 되지 않나요? 그러면 `user` 프롭의 타입에서 null은 빼주세요.

2024-07-13 11:28 UTC, joonhok-fittube commented on src/components/kakaoMap.tsx
> +  const [address, setAddress] = useState<{lat: number; lng: number}[]>([]);
여러 개의 주소를 저장하는 상태니까 `addresses`라고 합시다.

2024-07-13 11:28 UTC, joonhok-fittube commented on src/components/kakaoMap.tsx
> +    if (kakaoLoaded && reviews.length > 0) {
이런 코드를 작성할 때는 

```
if (!kakaoLoaded) {
  return;
}
if (reviews.length > 0) {
 ...
}
```

이렇게 나누는 것이 더 간명하고 이해하기 쉽습니다. 그리고 reviews.length > 0 조건은 없어도 될 것 같습니다.

2024-07-13 11:28 UTC, joonhok-fittube commented on src/components/kakaoMap.tsx
> +      {kakaoLoaded ? (
이런 부분도 마찬가지인데 이 리턴문 앞에서 

```
if (!kakaoLoaded) {
  return <p>지도 준비중...</p>
}
return (
<>
  <Script src= ...
  ...
</>
)

이렇게 나눠서 적는게 더 좋습니다.

2024-07-13 11:28 UTC, joonhok-fittube commented on src/components/mypage.tsx
> +  const UserUid = id;
이렇게 변수를 새로 선언하지 말고 처음부터 `id` 변수를 좀 더 이해하기 쉽게 `uid`라는 이름으로 주시면 좋겠습니다.

2024-07-13 11:28 UTC, joonhok-fittube commented on src/lib/requestdata.tsx
> +
밑에 `const requestUrl` 만드는 부분은 이 링크 참조해서 수정해주세요.

https://stackoverflow.com/a/73678107/1844500

2024-07-13 11:28 UTC, joonhok-fittube commented on src/data/firestore.tsx
> +// 리뷰 많이 작성한 top3출력 - firebase의 쿼리(orderby) 이용해 보려했으나 실패.
파이어스토어에 count 쿼리가 있긴 하지만 특정 사용자의 리뷰 개수를 조회하는데는 이용할 수 있어도 전체 리뷰를 사용자 별로 개수를 파악하는건 불가능합니다.
보통 이런 작업은 사용자별 리뷰 개수를 저장하고 관리하는 컬렉션을 하나 별도로 두고, 리뷰 컬렉션에 새로운 문서가 저장될 때마다 이 리뷰 개수 컬렉션을 업데이트하는 방식으로 처리합니다. 이 부분은 그런데 백엔드 쪽 내용이니 더 들어가지는 않으셔도 됩니다.

https://firebase.google.com/docs/firestore/query-data/aggregation-queries?_gl=1*lyih60*_up*MQ..*_ga*MjExNDMxMDQ4OS4xNzIwODY5NzUw*_ga_CW55HF8NVT*MTcyMDg2OTc1MC4xLjAuMTcyMDg2OTc1Ny4wLjAuMA..#use_the_count_aggregation

2024-07-15 07:54 UTC, jjisabi commented on src/components/basicLayout.tsx
> +  const moveMyPage = (e: number) => {
네! 수정하겠습니다.

2024-07-17 08:11 UTC, jjisabi commented on src/components/detailLayout.tsx
> +          item.IRREGULR_RELYSWIMPL_LANE_CNT) !== null ? (
타입을 하나 정의하고 1:1로 속성을 대응시키는 방법을 코드로 작성하는 방법을 모르겠습니다. 
우선 `request.tsx` 파일의 `dataArray.forEach`문에서 각각의 데이터를 넣어주었는데 멘토님께서 말씀해 주신 방법으로 해결 한 것은 아닌 것 같습니다. 원본 데이터의 타입과 맵핑할 데이터의 타입을 생성하고 변환 함수를 작성해야 할까요 ?

2024-07-17 08:12 UTC, jjisabi commented on src/components/header.tsx
>  const WithAuthenticatedUserControls = ({user}: {user: User | null}) => {
맞습니다. null 타입 제거했습니다.

2024-07-18 01:19 UTC, joonhok-fittube requested changes

2024-07-18 01:19 UTC, joonhok-fittube commented on src/ui/icon.tsx
> +export function AwardsIcon(topAuthors: any) {
이렇게 하면 코드 읽기도 어려워지고(어떤 로직으로 어떤 색깔이 칠해지는지 확인하려면 호출하는 쪽과 호출되는 쪽 양쪽을 다 봐야합니다) 실수하기도 쉬워집니다.

```
export function AwardsIcon(color: 'yellow' | 'grey' | 'orange' | 'currentColor') {
  ...
}
```
형태로 바꾸시고, 호출하는 쪽에서 topAuthors 인덱스에 따라 파라미터로 넘겨줄 색상 값을 정해서 넘겨주는 것이 더 좋겠습니다.

2024-07-18 01:19 UTC, joonhok-fittube commented on src/ui/icon.tsx
> +          props.index < Math.floor(props.reviews / 3) ? '#1079ea' : '#CCCCCC'
여기도 이렇게 설계가 되면 FishIcon 컴포넌트를 현재 이 맥락이 아닌 다른 맥락에서는 사용하기가 어려워집니다. FishIcon 컴포넌트에서는 색상을 프롭으로 받도록 하고, index나 reviews 같은 프롭은 받지 않도록 변경해주세요.

2024-07-18 01:19 UTC, joonhok-fittube commented on src/ui/icon.tsx
> +    <>
이미 탑레벨 노드가 있기 때문에 Fragment를 또 쓸 필요가 없습니다.  Fragment를 언제쓰는 것인지, 왜 쓰는 것인지 공부해보세요.

2024-07-18 01:19 UTC, joonhok-fittube commented on src/ui/icon.tsx
> +      <Tooltip content={userLevelLabel(props.index)} key={props.index}>
이 툴팁은 여기 있는게 아니라 원래 자리에 있는 것이 맞습니다. 왜냐하면 이 컴포넌트 이름이 FishIcon이고, 이름 그대로 아이콘을 리턴하는 것이 맞기 때문입니다. FishIcon은 어떤 경우라도 항상 툴팁과 같이 보여줘야 하나요? 만약 그렇다면 이름도 FishIconWithTooltip 정도로 바꾸고 이 파일 위치도 /src/ui/icon이 아니라 별도의 파일로 옮기시는게 낫습니다.

2024-07-18 06:48 UTC, jjisabi commented on src/components/header.tsx
> -          <svg
처음엔 의도하지는 않았는데, 로그인 정보가 있을때는 로그인 아이디를 표시하고 아이콘은 빼는 게 더 나아보여서 따로 추가하지 않았습니다!

2024-07-18 06:49 UTC, jjisabi commented on src/ui/icon.tsx
> +      className="text-blue-500 inline-flex items-center size-7"
네! 속성으로 넘기도록 수정하였습니다.

2024-07-18 06:52 UTC, jjisabi commented on src/ui/icon.tsx
> +export function AwardsIcon(topAuthors: any) {
`({color}: {color: string})` type으로 받고 호출하는 곳에서 `getSvgColor()` 함수에서 넘겨 줄 색상 값을 정하도록 수정했습니다. 더 나은 방법으로 수정하는 방법이 있을까요 ?

2024-07-18 06:56 UTC, jjisabi commented on src/ui/icon.tsx
> +      <Tooltip content={userLevelLabel(props.index)} key={props.index}>
현재까지는 FishIcon이 툴팁과 같이 보여주는 경우 밖에 없긴 하지만, 따로 분리하는 것이 맞는 것 같습니다.
툴팁에서 FishIcon  컴포넌트 접근이 안되는 에러가 발생하여 `forwardRef`를 사용하여 `ref`, `props`를 전달하였습니다.

2024-07-18 07:00 UTC, jjisabi commented on src/ui/icon.tsx
> +    <>
넵 ! react의 component에서는 하나의 element만 반환해야 하니까 1개 이상의 태그들을 사용할 때 최상단 태그 역할 할 때 사용하는 건데 이 부분에서는 <svg>태그가 하나이므로 필요가 없습니다.

2024-07-18 07:54 UTC, joonhok-fittube commented on src/components/header.tsx
> -          <svg
아, 일부러 빼신 거면 괜찮습니다. 저는 혹시 실수로 빠트리셨나했습니다.

2024-07-18 07:54 UTC, joonhok-fittube commented on src/ui/icon.tsx
> +export function AwardsIcon(topAuthors: any) {
아니요, 그렇게 하셔도 됩니다.

2024-07-18 07:57 UTC, joonhok-fittube approved these changes
수고하셨습니다!

2024-07-18 08:09 UTC, jjisabi commented on src/components/header.tsx
> -          <svg
아! 네! 확인해 주셔서 감사합니다!

2024-07-18 08:09 UTC, merged